sudo: false
language: c
compiler:
  - gcc -std=c99
  - clang
addons:
  apt:
    packages:
    - gperf
    
install:
    - git clone https://github.com/saitoha/libsixel.git
    - cd libsixel && ./configure --prefix=$HOME && make && make install && cd ..
    
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-sixel/.travis_build_config.rb build_config.rb
script:
  - export PKG_CONFIG_PATH=$HOME/lib/pkgconfig
  - make all test
